### ISSUE TITLE
Additional dependencies

### ISSUE THREAD

**Issue by quatermain** [bitwalker/alpine-elixir#12]
Hello,
first thanks for your really good work.  But how can I add some dependencies to your alpine docker image. Right know we need to add `apk add erlang-xmerl` but when I use it install also erlang 19 but we want to use 20. Is it possible to install so our pheonix app will see xmerl?

**Comment by bitwalker** [comment]
In the short term, I would take this Dockerfile, and modify it to remove the stripping of xmerl (and any other Erlang apps you may need), then rebuild the image with your customizations. Since it's a common enough dependency, I'll see how much an impact it is to add xmerl to the list of applications included in the default image, but the general idea is that if you need a larger subset of apps, you can build off this image easily by customizing the build parameters.

**Comment by quatermain** [comment]
thanks for answer, sorry for my delay. Any hints how to add this kind of app/dependency to build please?

**Comment by quatermain** [comment]
I used docker file from this post https://elixirforum.com/t/smallest-docker-container-with-elixir-app/6975/24 like example and it helped me. Thanks for you time
