### ISSUE TITLE
Question: Image sizes

### ISSUE THREAD

**Issue by bjuretic** [bitwalker/alpine-elixir#26]
Hi,

I'm just looking at the image sizes for the empty containers:

```
$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
bitwalker/alpine-elixir   latest              d814edb83fe0        4 days ago          144MB
bitwalker/alpine-erlang   latest              e5c5ce95529b        7 days ago          120MB
```

This is Java-size :)

Many people were reporting significantly smaller sizes so I'm trying to understand if this is normal?

**Comment by bitwalker** [comment]
Well, they aren't empty :P, but I did some looking because they weren't that large in the past. Looks like things may have creeped up over time, I stripped some extra stuff now and the size for `alpine-erlang` is down to 76.2mb, and `alpine-elixir` is down to 98.1. Docker Hub shows them at about 45 and 55mb, respectively, which I assume is accounting for sharing layers.

The Elixir image builds on the Erlang image, which has a full Erlang installation in it, plus some associated tools required for building with NIFs, some required system libraries like OpenSSL. The Elixir image adds `make`, `git`, `rebar`, `hex`, plus the Elixir binaries/beams. Tools required only for building Erlang are stripped out during the image build.

I'm open to suggestions for reducing the image size further, but at this point I don't see any way to do so that doesn't compromise the general utility of the image. If you need really stripped down images, the only way to do that right is to build your own variant of this image which removes everything except what you need.
