### ISSUE TITLE
Dockerfile now references Erlang/OTP20 but Elixir 1.4.5 is required for compatibility. 

### ISSUE THREAD

**Issue by idyll** [bitwalker/alpine-elixir#4]
You may want to change:
`bitwalker/alpine-erlang:latest`
to 
`bitwalker/alpine-erlang:19.3.4`
for this version?

**Comment by bitwalker** [comment]
I'll just update the Dockerfile to reference 1.4.5 ;)

**Comment by bitwalker** [comment]
I've tagged 1.4.5-OTP19 and 1.4.5 (which uses `latest`, i.e. OTP20), and published both to Docker Hub as well.

**Comment by sinorga** [comment]
Hi, I would suggest not to use the `latest` tag. It seems hard to track which version of alpine-erlang image is used. It depends on the moment you build the `alpine-elixir` image if my understanding is correct.

**Comment by bitwalker** [comment]
I can make the change. I originally wasn't expecting people to consume this repo directly nearly as often as consuming the images from Docker Hub, and I coordinate the publication of `alpine-erlang` and `alpine-elixir` so that when a new version of one or the other comes out, I update the upstream images, i.e. when `OTP 19` came out, I published `alpine-erlang:19.x.x`, and published the latest version of Elixir at the time using the new `alpine-erlang` as a base image. That said, it seems like it's more common that people are using the repos and using their own private registries, so I agree using tagged images is best.

**Comment by sinorga** [comment]
Thanks a lot. 👍
