### ISSUE TITLE
Tags to fix version

### ISSUE THREAD

**Issue by jfrolich** [bitwalker/alpine-elixir#46]
We were using 1.9.1, but the upgrade to OTP 22.1 broke hackney, resulting in an outage on our servers. Would it be possible to have stable version tags? So a build to a specific point version would not have breaking changes?

**Comment by bitwalker** [comment]
I recommend maintaining your own Docker repository which you pull (or push) images into, that way you have control over the release cycle. I deliberately don't guarantee that kind of stability due to the maintenance burden, as well as the fact that the current tagging scheme doesn't provide for any way to express updates to Alpine or OTP while 1.9.1, for example, is the current latest release. I provide my builds on Docker Hub for convenience, but for anything serious you should not rely on my builds directly.

That said, I'm open to alternative schemes as long as they can be fully automated like the current scheme is, and as long as the scheme is such that the intuitive tag, say `alpine-elixir:1.9.1` is the more fluid release cycle.

In general though, it is best to maintain your own image repository, since it is completely within your control, and avoids the possibility of the images shifting from under you. Maintaining your own repo can be as simple as just creating your own account on Docker Hub, modifying the build for as needed, and then running `make release`. You can also pull my builds, and then push them to your account just once per tag, but its best to just do the builds yourself in my opinion.
