### ISSUE TITLE
ERROR: failed to solve: ***/alpine-erlang:26.0.1: no match for platform in manifest sha256:8c6c0bd05724b421731232d1fe60edc0e48d32b19b131d7713b1086ffa697378: not found

### ISSUE THREAD

**Issue by drmartinberger** [bitwalker/alpine-elixir#77]
https://github.com/bitwalker/alpine-elixir/actions/runs/5416369824/jobs/9845999491

**Comment by drmartinberger** [comment]
Hi @bitwalker, any idea what went wrong when publishing the image to Docker Hub?

**Comment by bitwalker** [comment]
The build failed due to the lack of the ARM64 build in `alpine-erlang`, which is temporarily disabled due to an issue with QEMU and Erlang/OTP 25+. I've temporarily disabled that build in this repo as well, and the image should be up on Docker Hub shortly (for x86_64 hosts anyway).

I'm awaiting a [fix](https://gitlab.com/qemu-project/qemu/-/issues/1034) for QEMU before I re-enable the ARM64 builds, since for now CI builds are just broken for ARM. If I can find time, I may run the builds locally and push those, but for now people that want to use this image on ARM machines will need to build it themselves.

**Comment by drmartinberger** [comment]
Thanks for the info!
